### ISSUE TITLE
Rule 23 does not consider non-persistable objects

### ISSUE THREAD

**Issue by FredPetrignani** [Omnext/omnext.github.io#10]
In our Omnext result, there is a Critical Violation that we can't process.

The violation is that according to Omnext a filter is applied on a retrieve action, but that the list that the filter is applied to is not used further down. The suggestion is to apply the filter in the XPath constraint, so that we only get the list that we need. 

However, the retrieve is “by association” (because it concerns non-persistable objects) and within a retrieve "by association” we cannot apply an XPath constraint. That's why we use a List Operation (“Find”) after the retrieve, with a filter to find the correct object.

This violation (Rule 23) should only occur if the object that is being retrieved is persistable, because only on persistable objects can you use XPath.

**Comment by JohnCornegge** [comment]
I can backup Frederics issue.
This should not cause a violation as there is no other way to apply an XPath constraint to a retrieve over an association.

**Comment by mendixfittest** [comment]
This item has been implemented by Omnext and will be part of the next release.
